version: '3.1'

services:
  postgres:
    container_name: postgresex
    image: postgres:15.4-alpine3.17
    networks:
      - value8-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
networks:
  value8-network:
    external: true