version: '3.1'

services:
  mysql8:
    container_name: mysql8
    image: mysql:8.1.0
    networks:
      - value8-network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-conf/conf:/etc/mysql/conf.d
    restart: always
volumes:
  mysql_data:
    driver: local
networks:
  value8-network:
    external: true